config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  
  root "home#index"
  resources :games

  resources :home, only: :index
  get "contact", to: "home#contact_new"
  post "contact", to: "home#contact_create"

  resources :chats
  resources :messages, only: [:index, :create] do
    collection do
      get :new_chat
    end
  end
 
  resources :aimages

  resources :sounds


  mount Sidekiq::Web => "/sidekiq"
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  enum role: { system: 0, assistant: 10, user: 20 }

  belongs_to :chat, optional: true

  broadcasts_to ->(message) { "messages" }, inserts_by: :append

  scope :ordered, -> { order(id: :desc) }


  def self.for_openai(messages)
    messages.map { |message| { role: message.role, content: message.content } }
  end

  def assistant_message?
    role == "assistant"
  end

  private

  def chat_must_exist
    errors.add(:chat, "must exist") unless chat.present?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @chats = Chat.all.order(created_at: :desc)
    @message = Message.new
    @messages = Message.where(chat_id: params[:chat_id]).order(created_at: :asc)
    mark_messages_as_viewed(@messages)
    @aimages = Aimage.all
    @sounds = Sound.all
   
  end
  
  def create
    if params[:new_chat].present?
      initialize_chat
    else
      @message = Message.new(role: "user", content: message_params[:content])
  
      if session[:chat_id].nil?
        initialize_chat
      else
        @chat = Chat.find_by(id: session[:chat_id]) || current_user.chats.create!
        session[:chat_id] = @chat.id
      end
  
      @message.chat_id = @chat.id
      @message.role = "user"
  
      @chat.update(name: @message.content&.slice(0, 10))
  
       
          if @message.save
            GetAiResponseJob.perform_async(@message.chat_id)
         

            respond_to do |format|
              format.html { redirect_to message_path(@message), notice: "message was successfully created." }
              format.turbo_stream
            end
          end
    end
  end

  def new_chat
    initialize_chat
  
    respond_to do |format|
      format.html { redirect_to messages_path(chat_id: @chat.id) }
      format.turbo_stream
    end
  end

  private

  def initialize_chat
    @chat = Chat.create!(user_id: current_user.id)
    session[:chat_id] = @chat.id
  end

  def mark_messages_as_viewed(messages)
    messages.each do |message|
      message.update(viewed: true) unless message.viewed?
    end
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/messages/_form.html.erb
 
<div class="fixed bottom-0 mb-4" style="position: fixed; bottom: 0; right: 20px; left: 370px;">
  <%= form_with(model: @message, url: messages_path, local: true, class: "flex items-center", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset", turbo_frame: "messages" }) do |form| %>
    <!-- Form fields -->
    <div class="flex-1">
     <%= form.text_field :content, class: "w-full border-gray-300 rounded-l-lg py-2 px-4", placeholder: "Type your message..." %>


    </div>
    <div class="p-8">
      <%= form.button raw('<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>'), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg" %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag message do %>
  <div id="<%= dom_id(message) %>_messages">
    <% if message.user? %>
      <div class="m-8 p-4 flex items-start break-all">
        <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000" class="mr-2">
          <g>
            <rect fill="none" height="24" width="24"/>
          </g>
          <g>
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 4c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm0 14c-2.03 0-4.43-.82-6.14-2.88C7.55 15.8 9.68 15 12 15s4.45.8 6.14 2.12C16.43 19.18 14.03 20 12 20z"/>
          </g>
        </svg>
        <div><%= message.content %></div>
      </div>
    <% else %>
      <div class="m-8 p-4 flex ">
        <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="48px" viewBox="0 0 24 24" width="48px" fill="#000000" class="mr-2">
          <rect fill="none" height="24" width="24" y="0"/>
          <path d="M7,20h4c0,1.1-0.9,2-2,2S7,21.1,7,20z M5,19h8v-2H5V19z M16.5,9.5c0,3.82-2.66,5.86-3.77,6.5H5.27 C4.16,15.36,1.5,13.32,1.5,9.5C1.5,5.36,4.86,2,9,2S16.5,5.36,16.5,9.5z M21.37,7.37L20,8l1.37,0.63L22,10l0.63-1.37L24,8 l-1.37-0.63L22,6L21.37,7.37z M19,6l0.94-2.06L22,3l-2.06-0.94L19,0l-0.94,2.06L16,3l2.06,0.94L19,6z"/>
        </svg>
        <% if message.loader? %>
          <div class="typing-loader"></div>
        <% else %>
         <div class="message" data-controller="typing" data-viewed="<%= message.viewed %>" data-target="typing.output">
  <%= render_markdown_with_code_highlighting(message.content) %>
</div>

        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages", @message, scroll_to: true %>
<%= turbo_stream.append "chats", @chat %>




 

app/views/messages/destroy.turbo_stream.erb
<%= turbo_stream.remove @message %>
<%= render_turbo_stream_flash_messages %>

app/views/messages/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to user"), user_path(@user) %>

  <div class="header">
    <h1>Edit item</h1>
  </div>

  <%= turbo_frame_tag @message do %>
    <%= render "form",
              user: @user,
              message_content: @message_content,
              message: @message %>
  <% end %>
</main>

app/views/messages/index.html.erb
<%= turbo_stream_from "chats" %>
<%= turbo_stream_from "messages" %>
<%= turbo_stream_from "aimages" %>
<%= turbo_stream_from "sounds" %>
<div class="flex">
  <div class="h-screen w-1/4 bg-gray-800 p-4">
    <div class="mb-4 flex flex-col">
    
      <span class="border border-slate-400 rounded-lg px-4 py-2 mb-4 flex items-center justify-center hover:bg-gray-700">
        <svg xmlns="http://www.w3.org/2000/svg" fill="#fff" height="24" viewBox="0 -960 960 960" width="24">
          <path d="M450-200v-250H200v-60h250v-250h60v250h250v60H510v250h-60Z" />
        </svg>
        <%= link_to "New Chat", new_chat_messages_path, class: "ml-2 text-white", turbo_stream: true %>
      </span>

      <span class="border border-slate-400 rounded-lg px-4 py-2  mb-4 flex items-center justify-center hover:bg-gray-700">
        <svg xmlns="http://www.w3.org/2000/svg" fill="#fff" height="24" viewBox="0 -960 960 960" width="24">
          <path d="M450-200v-250H200v-60h250v-250h60v250h250v60H510v250h-60Z" />
        </svg>
        <%= link_to "New Image", new_aimage_path, data: { turbo_frame: dom_id(Aimage.new) }, class: "ml-2 text-white" %>
        <%= turbo_frame_tag Aimage.new %>
      </span>

      <span class="border border-slate-400 rounded-lg px-4 py-2 mb-4 flex gap-4 items-center justify-center hover:bg-gray-700">
        <%= link_to sounds_path, data: { turbo_frame: 'sounds' }, class: "ml-2 text-white" do %>
          <%= content_tag :svg, xmlns: "http://www.w3.org/2000/svg", fill: "#fff", height: "24", viewBox: "0 -960 960 960", width: "24" do %>
            <%= content_tag :path, nil, d: "M450-200v-250H200v-60h250v-250h60v250h250v60H510v250h-60Z" %>
          <% end %>
        <% end %>
        <h2 class="text-white">Music</h2>
        <%= link_to messages_path do %>
          <%= content_tag :svg, xmlns: "http://www.w3.org/2000/svg", shape_rendering: "geometricPrecision", text_rendering: "geometricPrecision", image_rendering: "optimizeQuality", fill_rule: "evenodd", clip_rule: "evenodd", viewBox: "0 0 512 511.99", width: "24", height: "24" do %>
            <%= content_tag :path, nil, fill: "#FC4032", fill_rule: "nonzero", d: "M256 0c70.68 0 134.68 28.67 181.01 74.99 46.32 46.32 74.99 110.32 74.99 181S483.33 390.68 437.01 437c-46.33 46.33-110.33 74.99-181.01 74.99-70.68 0-134.68-28.66-181.01-74.99C28.67 390.68 0 326.67 0 255.99c0-70.68 28.67-134.68 74.99-181C121.32 28.67 185.32 0 256 0z" %>
            <%= content_tag :path, nil, fill: "#fff", d: "M381.4 234.68v42.63c0 10.08-8.3 18.38-18.38 18.38H148.98c-10.08 0-18.38-8.26-18.38-18.38v-42.63c0-10.12 8.26-18.38 18.38-18.38h214.04c10.12 0 18.38 8.33 18.38 18.38z" %>
          <% end %>
        <% end %>
      </span>
      
      <div>
        <%= turbo_frame_tag 'sounds' %>
      </div>
    </div>
    <div class="flex flex-col">
      <%= turbo_frame_tag 'chats' do %>
        <%= render @chats %>
      <% end %>
      <%= turbo_frame_tag 'aimages' do %>
        <%= render @aimages %>
      <% end %>
    </div>
  </div>
  <div class="flex-1 p-4 flex flex-col">
    <%= turbo_frame_tag "messages", data: { controller: "scroll" } do %>
      <div id="messages">
        <%= render @messages %>
      </div>
    <% end %>
    <div class="">
      <%= render 'form', message: @message , data: { turbo_frame: 'messages'} %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to user"), user_chats_path(@user) %>

  <div class="header">
    <h1>New message for <%= @chat.id %></h1>
  </div>

  <%= turbo_frame_tag nested_dom_id(@chat, Message.new) do %>
    <%= render partial: "form", locals: {user: @user, chat: @chat, message: @message} %>
   
  <% end %>
</main>

app/views/messages/update.turbo_stream.erb
<%= turbo_stream.update "messages", @message,  scroll_to: true %>