config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  
  root "home#index"
  resources :games

  resources :home, only: :index
  get "contact", to: "home#contact_new"
  post "contact", to: "home#contact_create"

  resources :chats
  resources :messages, only: [:index, :create] do
    collection do
      get :new_chat
    end
  end
 
  resources :aimages

  resources :sounds


  mount Sidekiq::Web => "/sidekiq"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @games = Game.all
    @game = Game.new
  end
  
  
  def contact_new
    @contact_form = if current_user
      ContactForm.new(
        email: current_user.email
      )
    else
      ContactForm.new
    end
  end

  def contact_create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      UserMailer.contact(@contact_form).deliver
      flash.now[:notice] = "Your email is sent"
      @contact_form.text = ""
    end
    render :contact_new
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(
      *ContactForm::FIELDS
    )
  end
end

app/views/home/contact_new.html.erb
<section class="h-full text-gray-800 overflow-y-auto">
    <div class="-mt-36 lg:m-0 pt-0 overflow-hidden bg-no-repeat bg-cover"
      style="background-position: 50%; background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg'); height: 300px;">
    </div>
    <div class="container text-gray-800 px-4 md:px-12">
      <div class="block rounded-lg shadow-lg py-10 md:py-12 px-4 md:px-6"
        style="margin-top: -100px; background: hsla(0, 0%, 100%, 0.8); backdrop-filter: blur(30px);">
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-x-6 mb-12 text-sm lg:text-base">
          <div class="mb-12 lg:mb-0  text-center mx-auto">
            <svg class="w-8 h-8 text-blue-600 mb-6 mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M248 8C111.03 8 0 119.03 0 256s111.03 248 248 248 248-111.03 248-248S384.97 8 248 8zm82.29 357.6c-3.9 3.88-7.99 7.95-11.31 11.28-2.99 3-5.1 6.7-6.17 10.71-1.51 5.66-2.73 11.38-4.77 16.87l-17.39 46.85c-13.76 3-28 4.69-42.65 4.69v-27.38c1.69-12.62-7.64-36.26-22.63-51.25-6-6-9.37-14.14-9.37-22.63v-32.01c0-11.64-6.27-22.34-16.46-27.97-14.37-7.95-34.81-19.06-48.81-26.11-11.48-5.78-22.1-13.14-31.65-21.75l-.8-.72a114.792 114.792 0 0 1-18.06-20.74c-9.38-13.77-24.66-36.42-34.59-51.14 20.47-45.5 57.36-82.04 103.2-101.89l24.01 12.01C203.48 89.74 216 82.01 216 70.11v-11.3c7.99-1.29 16.12-2.11 24.39-2.42l28.3 28.3c6.25 6.25 6.25 16.38 0 22.63L264 112l-10.34 10.34c-3.12 3.12-3.12 8.19 0 11.31l4.69 4.69c3.12 3.12 3.12 8.19 0 11.31l-8 8a8.008 8.008 0 0 1-5.66 2.34h-8.99c-2.08 0-4.08.81-5.58 2.27l-9.92 9.65a8.008 8.008 0 0 0-1.58 9.31l15.59 31.19c2.66 5.32-1.21 11.58-7.15 11.58h-5.64c-1.93 0-3.79-.7-5.24-1.96l-9.28-8.06a16.017 16.017 0 0 0-15.55-3.1l-31.17 10.39a11.95 11.95 0 0 0-8.17 11.34c0 4.53 2.56 8.66 6.61 10.69l11.08 5.54c9.41 4.71 19.79 7.16 30.31 7.16s22.59 27.29 32 32h66.75c8.49 0 16.62 3.37 22.63 9.37l13.69 13.69a30.503 30.503 0 0 1 8.93 21.57 46.536 46.536 0 0 1-13.72 32.98zM417 274.25c-5.79-1.45-10.84-5-14.15-9.97l-17.98-26.97a23.97 23.97 0 0 1 0-26.62l19.59-29.38c2.32-3.47 5.5-6.29 9.24-8.15l12.98-6.49C440.2 193.59 448 223.87 448 256c0 8.67-.74 17.16-1.82 25.54L417 274.25z"/></svg>
            <h6 class="font-medium">Europe</h6>
          </div>
          <div class="mb-12 lg:mb-0 text-center mx-auto">
            <svg class="w-8 h-8 text-blue-600 mb-6 mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="currentColor" d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"></path></svg>
            <h6 class="font-medium">Athena, 48 092</h6>
          </div>
          <div class="mb-6 md:mb-0 text-center mx-auto">
            <svg class="w-8 h-8 text-blue-600 mb-6 mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M493.4 24.6l-104-24c-11.3-2.6-22.9 3.3-27.5 13.9l-48 112c-4.2 9.8-1.4 21.3 6.9 28l60.6 49.6c-36 76.7-98.9 140.5-177.2 177.2l-49.6-60.6c-6.8-8.3-18.2-11.1-28-6.9l-112 48C3.9 366.5-2 378.1.6 389.4l24 104C27.1 504.2 36.7 512 48 512c256.1 0 464-207.5 464-464 0-11.2-7.7-20.9-18.6-23.4z"></path></svg>
            <h6 class="font-medium">+ 050 059 483 574</h6>
          </div>
          <div class="text-center mx-auto">
            <a href="" target="_blank"><svg class="w-8 h-8 text-blue-600 mb-6 mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill="currentColor" d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path></svg></a>
            <h6 class="font-medium">Facebook Page</h6>
          </div>
        </div>
        <div class="max-w-[700px] mx-auto">
          <%= simple_form_for @contact_form, url: contact_path,
                    html: {
                      class: "space-y-8",
                      data: { turbo: false }
                    } do |f| %>
        <% if @contact_form.errors.any? %>
          <div class="text-red-500">
            <%= @contact_form.errors.full_messages.to_sentence.capitalize %>
          </div>
        <% end %>
            <div class="form-group mb-6">
              <%= f.email_field :email, input_html: { autofocus: true }, id: "contact-email-input", class: "form-control block
              w-full
              px-3
              py-1.5
              text-base
              font-normal
              text-gray-700
              bg-white bg-clip-padding
              border border-solid border-gray-300
              rounded
              transition
              ease-in-out
              m-0
              focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none", placeholder: "Email address"%>
            </div>
            <div class="form-group mb-6">
              <%= f.text_area :text, input_html: { autofocus: true }, rows: "6", class: "    form-control
              block
              w-full
              px-3
              py-1.5
              text-base
              font-normal
              text-gray-700
              bg-white bg-clip-padding
              border border-solid border-gray-300
              rounded
              transition
              ease-in-out
              m-0
              focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
            ", placeholder: "Message" %>
            </div>
            <%= f.submit 'Send Email', class: "w-full
            px-6
            py-2.5
            bg-blue-600
            text-white
            font-medium
            text-xs
            leading-tight
            uppercase
            rounded
            shadow-md
            hover:bg-blue-700 hover:shadow-lg
            focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
            active:bg-blue-800 active:shadow-lg
            transition
            duration-150
            ease-in-out" %>
          <% end %>
        </div>
      </div>
      </div>
  </section>

app/views/home/index.html.erb
<section class="bg-gray-100 overflow-scroll">
  <header class="bg-white py-6">
    <div class="container mx-auto px-4">
      <h1 class="text-3xl text-center text-gray-800 font-semibold">Chess Application</h1>
    </div>
  </header>

  <div class="container mx-auto px-4 mt-10">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div>
                 <%= image_tag "chess.png", alt: "Chess Image", class: "rounded-lg shadow-md" %>
      </div>
      <div class="flex flex-col overflow-auto">
        <div class="max-h-64">
          <h2 class="text-2xl text-gray-800 font-semibold mb-4">Master the Game of Chess</h2>
          <p class="text-gray-600 mb-4">This is a professional chess application built with modern Rails framework, Hotwire, and Stimulus. Experience the thrill of playing chess online with real-time updates.</p>
          <p class="text-gray-600 mb-4">Engage in strategic battles on the virtual chessboard, enhance your skills, and challenge opponents from around the world. Our intuitive interface and responsive design provide an immersive chess experience.</p>
        </div>
          <div class="flex justify-center text-center pt-8 mt-6 ">
        <% if user_signed_in? %>
          <%= link_to "Start", games_path, class: "btn btn--primary w-full py-3 px-6 text-white font-semibold rounded-lg shadow-md bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "btn btn--primary py-3 px-6 text-white font-semibold rounded-lg shadow-md bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
        <% end %>
    </div>
      </div>
    </div>
  </div>
</section>


  