config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  
  root "home#index"
  resources :games

  resources :home, only: :index
  get "contact", to: "home#contact_new"
  post "contact", to: "home#contact_create"

  resources :chats
  resources :messages, only: [:index, :create] do
    collection do
      get :new_chat
    end
  end
 
  resources :aimages

  resources :sounds


  mount Sidekiq::Web => "/sidekiq"
end

app/models/aimage.rb
class Aimage < ApplicationRecord
    validates :prompt, presence: true
    validates :size, presence: true

    broadcasts_to ->(aimage) { "aimages" }, inserts_by: :prepend
  end
  

app/controllers/aimages_controller.rb
class AimagesController < ApplicationController
    before_action :set_aimage, only: [:edit, :update, :destroy]

    def new
      @aimage = Aimage.new
    end
  
    def create
      @aimage = Aimage.new(aimage_params)
  
      if @aimage.save
        generate_aimage
        respond_to do |format|
            format.html { redirect_to aimage_path(@aimage), notice: "Aimage was successfully created." }
            format.turbo_stream
    end
  end
end
  
    def destroy
        @aimage.destroy
        respond_to do |format|
          format.html { redirect_to messages_path, notice: "aimage was successfully destroyed." }
          format.turbo_stream
        end
      end

    def update
        if @aimage.update(aimage_params)
          redirect_to messages_path, notice: "aimage was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
    end
  
    private

    def set_aimage
        @aimage = Aimage.find(params[:id])
      end
  
    def aimage_params
      params.require(:aimage).permit(:prompt, :size)
    end
  
    def generate_aimage
      openai_client = OpenAI::Client.new(access_token: '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')
    
      response = openai_client.images.generate(
        parameters: {
          prompt: @aimage.prompt,
          size: @aimage.size
        }
      )
    
      if response.key?("data")
        @aimage.url = response.dig("data", 0, "url")
        @aimage.save
      else
        flash[:alert] = 'Failed to generate aimage.'
      end
    end
  end
  

app/views/aimages/_aimage.html.erb
<%= turbo_frame_tag aimage do %>
  <main class="container mx-auto  py-4">
    <div class="flex flex-col bg-gray-100 rounded-lg">
      <% if aimage.url.present? %>
        <%= image_tag aimage.url %>
      <% else %>
        <div class="flex items-center justify-center bg-gray-800">
          <i class="fas fa-spinner fa-spin text-white text-4xl"></i>
        </div>
      <% end %>
      <div class="flex justify-center">
        <% if aimage.url.present? %>
          <%= button_to "Delete", aimage_path(aimage), method: :delete, class: " btn btn-size px-4  text-red-500 font-semibold rounded-lg shadow-md hover:text-red-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
      </div>
        <% end %>
      </div>
    </div>
  </main>
<% end %>

app/views/aimages/_form.html.erb
<%= form_with(model: @aimage, url: aimages_path, class: 'w-full max-w-sm') do |form| %>
  <div class="mb-4">
    <%= form.label :prompt, class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= form.text_area :prompt, class: 'form-textarea mt-1 block w-full' %>
  </div>

  <div class="mb-4">
    <%= form.label :size, class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= form.select :size, options_for_select(['256x256', '512x512', '1024x1024']), {}, class: 'form-select mt-1 block w-full' %>
  </div>

  <div class="flex flex-col items-center justify-between">
    <%= form.submit 'Generate Image',  data: { turbo_frame: dom_id(aimage) }, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    <%= link_to "Cancel", messages_path, class: " mt-4 btn btn-size py-1 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
  </div>
<% end %>

app/views/aimages/create.turbo_stream.erb
<%= turbo_stream.append "images", @aimage %>
<%= turbo_stream.update Aimage.new, "" %>

app/views/aimages/destroy.turbo.stream.erb
<%= turbo_stream.remove @aimage%>

app/views/aimages/new.html.erb
  <%= turbo_frame_tag @aimage do %>
    <%= render "form", aimage: @aimage %>
  <% end %>
</main>